### ISSUE TITLE
Compute score for color guessing game

### ISSUE THREAD

**Issue by skylerberg** [SageBerg/sageberg.com#1]
I like the color guessing game! It would be nice to get a score on it so that I can tell how far off I was.

You could compute how far off someone is by taking the difference for R, B, and G values and adding them together. This would score like golf; lower is better. To make higher better, this value could be subtracted from something like 255*3.

**Comment by SageBerg** [comment]
I actually implemented this feature earlier today, but hadn't pushed it to production yet. I pushed it so you can play with it. Let me know if you have any more ideas to improve it. I haven't styled it yet so that's something I can do. I'd also like to add client-side validation messages. The domain still isn't up, so you can use http://52.10.83.198/

**Comment by skylerberg** [comment]
Cool!
